# GENERALES
quarkus.application.name=GENDER
quarkus.http.port=8080

# BASE DE DATOS
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=moviedb
quarkus.datasource.password=1234
quarkus.datasource.reactive.url=postgresql://localhost:5432/movies

# ¡AÑADE ESTA LÍNEA PARA SOLUCIONAR EL ERROR!
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/movies

# LOGGING
#quarkus.log.level=INFO
#quarkus.log.category."org.jboss".level=DEBUG


# MONITOREO EN ELASTIC
#LOG_SERVICE=https://app-logger-producer-cfsmkmmchq-uc.a.run.app/logs
api.system=xxx
api.country=CL
#api.domain=legacy


# OPEN TELEMETRY
#QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://6038f05a78274527901b1a7c463ef53f.apm.us-central1.gcp.cloud.es.io:443
#QUARKUS_OTEL_EXPORTER_OTLP_TRACES_HEADERS=Authorization=Bearer ynRpbp3kmJqiRFhncm
#QUARKUS_OTEL_SERVICE_NAME=api-policies
#QUARKUS_OTEL_RESOURCE_ATRIBUTES=deployment.environment=local

# DOCUMENTACION
quarkus.smallrye-openapi.path=/api-docs
quarkus.swagger-ui.title=API-POLICIES
quarkus.swagger-ui.theme=original

# CORS
quarkus.http.cors=true
#quarkus.http.cors.origins=/.*/
#quarkus.http.cors.headers=Accept, Authorization, Content-Type
#quarkus.http.cors.methods=GET,PUT,POST,OPTIONS,DELETE

# HEALTH
#quarkus.redis.health.enabled=false

log.service=sssxxxx