# GENERALES
QUARKUS_APLICATION_NAME=API-POLICIES
SERVER_PORT=8080

# BASE DE DATOS
QUARKUS_DB_KIND=postgresql
QUARKUS_DATASOURCE_PASSWORD=moviedb
QUARKUS_DATASOURCE_USERNAME=1234
QUARKUS_DATASOURCE_URL=jdbc:postgresql://localhost:5432/movies
QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=20

# LOGGING
QUARKUS_LOG_LEVEL=INFO
QUARKUS_LOG_CATEGORY_JBOSS_MIN_LEVEL=DEBUG

# MONITOREO EN ELASTIC
LOG_SERVICE=https://app-logger-producer-cfsmkmmchq-uc.a.run.app/logs
API_SYSTEM=api-policies-dev
API_COUNTRY=CL
API_DOMAIN=legacy

# OPEN TELEMETRY
QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://6038f05a78274527901b1a7c463ef53f.apm.us-central1.gcp.cloud.es.io:443
QUARKUS_OTEL_EXPORTER_OTLP_TRACES_HEADERS=Authorization=Bearer ynRpbp3kmJqiRFhncm
QUARKUS_OTEL_SERVICE_NAME=api-policies
QUARKUS_OTEL_RESOURCE_ATRIBUTES=deployment.environment=local

# DOCUMENTACION
SPRING_DOC_API_DOCS_PATH=/api-docs
SPRING_DOC_SWAGGER_UI_OPERATION_SORTER=method
QUARKUS_SMALLRYE_OPENAPI_TITLE=API-POLICIES
QUARKUS_SWAGGER_UI_THEME=original

# CORS
QUARKUS_HTTP_CORS_ORIGINS=/.*/
QUARKUS_HTTP_CORS_HEADERS=Accept, Authorization, Content-Type
QUARKUS_HTTP_CORS_METHODS=GET,PUT,POST,OPTIONS,DELETE

# HEALTH
QUARKUS_REDIS_HEALTH_ENABLED=false
